-- 043 — Удаление Стратегии 2.0 (таблицы v2_s2_*).

DROP TABLE IF EXISTS v2_s2_reviews CASCADE;
DROP TABLE IF EXISTS v2_s2_prana CASCADE;
DROP TABLE IF EXISTS v2_s2_signals CASCADE;
DROP TABLE IF EXISTS v2_s2_evidence CASCADE;
DROP TABLE IF EXISTS v2_s2_month_outcomes CASCADE;
DROP TABLE IF EXISTS v2_s2_constraints CASCADE;
DROP TABLE IF EXISTS v2_s2_backlog CASCADE;
DROP TABLE IF EXISTS v2_s2_decisions CASCADE;
DROP TABLE IF EXISTS v2_s2_antipatterns CASCADE;
DROP TABLE IF EXISTS v2_s2_rules CASCADE;
DROP TABLE IF EXISTS v2_s2_bets CASCADE;
DROP TABLE IF EXISTS v2_s2_engines CASCADE;
DROP TABLE IF EXISTS v2_s2_goals CASCADE;
DROP TABLE IF EXISTS v2_s2_sprints CASCADE;
